spring:
  cloud:
    sentinel:
      transport:
        dashboard: ${nft.turbo.sentinel.url}
      datasource:
        flow:
          nacos:
            server-addr: ${nft.turbo.nacos.server.url}
            data-id: business-flow-rules
            group-id: SENTINEL_GROUP
            rule-type: FLOW
        param-flow:
          nacos:
            server-addr: ${nft.turbo.nacos.server.url}
            data-id: business-param-flow-rules
            group-id: SENTINEL_GROUP
            rule-type: PARAM_FLOW