CREATE TABLE `pay_order`
(
    `id`                       bigint         NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `gmt_create`               datetime       NOT NULL COMMENT '创建时间',
    `gmt_modified`             datetime       NOT NULL COMMENT '修改时间',
    `pay_order_id`             varchar(32)    NOT NULL COMMENT '支付单号',
    `payer_id`                 varchar(32)    NOT NULL COMMENT '付款方iD',
    `payer_type`               varchar(32)    NOT NULL COMMENT '付款方类型',
    `payee_id`                 varchar(32)    NOT NULL COMMENT '收款方id',
    `payee_type`               varchar(32)    NOT NULL COMMENT '收款方类型',
    `biz_no`                   varchar(128)   NOT NULL COMMENT '业务单号',
    `biz_type`                 varchar(32)    NOT NULL COMMENT '业务单类型',
    `order_amount`             decimal(18, 6) NOT NULL COMMENT '订单金额',
    `paid_amount`              decimal(18, 6) DEFAULT NULL COMMENT '已支付金额',
    `channel_stream_id`        varchar(64)    DEFAULT NULL COMMENT '渠道流水号',
    `pay_url`                  varchar(512)   DEFAULT NULL COMMENT '支付地址',
    `pay_channel`              varchar(64)    NOT NULL COMMENT '支付方式',
    `memo`                     varchar(512)   DEFAULT NULL COMMENT '备注',
    `order_state`              varchar(64)    NOT NULL COMMENT '单据类型',
    `pay_succeed_time`         datetime       DEFAULT NULL COMMENT '支付成功时间',
    `pay_failed_time`          datetime       DEFAULT NULL COMMENT '支付失败时间',
    `pay_expire_time`          datetime       DEFAULT NULL COMMENT '支付超时时间',
    `deleted`                  tinyint        DEFAULT NULL COMMENT '逻辑删除标识',
    `lock_version`             int            DEFAULT NULL COMMENT '乐观锁版本号',
    `refunded_amount`          decimal(18, 6) DEFAULT NULL COMMENT '退款金额',
    `refund_channel_stream_id` varchar(64)    DEFAULT NULL COMMENT '退款流水号'
);


CREATE TABLE `pay_check_mismatch_detail`
(
    id                      bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `gmt_create`            datetime    NOT NULL COMMENT '创建时间',
    `gmt_modified`          datetime    NOT NULL COMMENT '修改时间',
    `pay_order_id`          varchar(64) NOT NULL COMMENT '支付单号',
    `channel_stream_id`     varchar(64)    DEFAULT NULL COMMENT '渠道流水号',
    `check_time`            datetime    NOT NULL COMMENT '核对时间',
    `pay_order_state`       varchar(32)    DEFAULT NULL COMMENT '支付单状态',
    `channel_stream_state`  varchar(32)    DEFAULT NULL COMMENT '渠道流水状态',
    `pay_order_amount`      decimal(10, 2) DEFAULT NULL COMMENT '支付单金额',
    `channel_stream_amount` decimal(10, 2) DEFAULT NULL COMMENT '渠道流水金额',
    `pay_order_time`        datetime       DEFAULT NULL COMMENT '支付单时间',
    `channel_stream_time`   datetime       DEFAULT NULL COMMENT '渠道流水时间',
    `mismatch_type`         varchar(64) NOT NULL COMMENT '不一致类型',
    `is_daily_cut`          tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否是日切相关数据: 0-否, 1-是',
    `deleted`               tinyint        DEFAULT NULL COMMENT '逻辑删除标识',
    `lock_version`          int            DEFAULT NULL COMMENT '乐观锁版本号',
    status                  varchar(32)    DEFAULT 'INIT' COMMENT '状态: INIT-初始状态, SUSPEND-挂起状态, FINISH-完成状态'
);


CREATE TABLE `wechat_transaction`
(
    `id`                     bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `date`                   datetime       NOT NULL COMMENT '交易时间',
    `app_id`                 varchar(64)    NOT NULL COMMENT '公众账号ID',
    `mch_id`                 varchar(64)    NOT NULL COMMENT '商户号',
    `sub_mch_id`             varchar(64)             DEFAULT NULL COMMENT '子商户号/特约商户号',
    `device_info`            varchar(128)            DEFAULT NULL COMMENT '设备号',
    `wechat_order_no`        varchar(128)   NOT NULL COMMENT '微信订单号',
    `mch_order_no`           varchar(128)   NOT NULL COMMENT '商户订单号',
    `user_id`                varchar(128)   NOT NULL COMMENT '用户标识',
    `type`                   varchar(64)    NOT NULL COMMENT '交易类型',
    `status`                 varchar(64)    NOT NULL COMMENT '交易状态',
    `bank`                   varchar(128)            DEFAULT NULL COMMENT '付款银行',
    `currency`               varchar(32)             DEFAULT NULL COMMENT '货币种类',
    `amount`                 decimal(18, 6) NOT NULL COMMENT '总金额',
    `envelope_amount`        decimal(18, 6)          DEFAULT NULL COMMENT '企业红包金额/代金券金额',
    `name`                   varchar(255)            DEFAULT NULL COMMENT '商品名称',
    `packet`                 text COMMENT '商户数据包',
    `poundage`               decimal(18, 6)          DEFAULT NULL COMMENT '手续费',
    `rate`                   varchar(32)             DEFAULT NULL COMMENT '费率',
    `order_amount`           decimal(18, 6)          DEFAULT NULL COMMENT '订单金额',
    `gmt_create`             datetime       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `gmt_modified`           datetime       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted`                tinyint                 DEFAULT '0' COMMENT 'l是否逻辑删除，0为未删除，非0为已删除''',
    `lock_version`           int            NOT NULL COMMENT '乐观锁版本号',
    `refund_apply_time`      datetime                DEFAULT NULL COMMENT '退款申请时间',
    `refund_success_time`    datetime                DEFAULT NULL COMMENT '退款成功时间',
    `wx_refund_order_no`     varchar(255)            DEFAULT NULL COMMENT '微信退款单号',
    `mch_refund_order_no`    varchar(255)            DEFAULT NULL COMMENT '商户退款单号',
    `refund_amount`          decimal(18, 6)          DEFAULT NULL COMMENT '退款金额',
    `envelope_refund_amount` decimal(18, 6)          DEFAULT NULL COMMENT '充值券退款金额',
    `refund_type`            varchar(64)             DEFAULT NULL COMMENT '退款类型',
    `refund_status`          varchar(64)             DEFAULT NULL COMMENT '退款状态',
    `apply_refund_amount`    decimal(18, 6)          DEFAULT NULL COMMENT '申请退款金额',
);